openapi: '3.0.3'
info:
  version: 0.0.1
  title: Cards Service
servers:
  - url: http://localhost
    description: local
#  - url: https://dev.store.com
#    description: development
#  - url: https://stage.store.com
#    description: stage

paths:
  /cards:
    post:
      tags:
        - "Cards"
      summary: "Generate a range of cards"
      parameters:
        - name: range
          in: query
          description: "Range of cards to be created"
          schema:
            type: integer
      responses:
        "200":
          description: "Task has been created"

  /cards/release/{customerId}/{cardId}:
    post:
      tags:
        - "Cards"
      summary: "Release a card to customer"
      parameters:
        - name: customerId
          in: path
          description: "Customer identifier"
          required: true
          schema:
            type: integer
        - name: cardId
          in: path
          description: "Card identifier"
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Card has been released"
        "400":
          description: "Invalid customerId or cardId parameters"
        "404":
          description: "Card or customer not found"
  /cards/block/{cardId}:
    post:
      tags:
        - "Cards"
      summary: "Card blocking by the customer or user"
      parameters:
        - name: cardId
          in: path
          description: "Card identifier"
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Card has been blocked"
        "400":
          description: "Invalid cardId parameter"
        "404":
          description: "Card not found"

  /cards/list:
    get:
      tags:
        - "Cards"
      summary: "Getting a list of all cards"
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: "Successful"

  /cards/list/free:
    get:
      tags:
        - "Cards"
      summary: "Getting a list of free cards"
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: "Successful"

#components:
#  schemas:
#    generateCards:
#      type: object
#      required:
#        -
#      properties:
#        number:
#          type: integer
#          example: "100"
#          required: true
