openapi: '3.0.3'
info:
  version: 1.0.0
  title: Test OpenAPI Contract
  termsOfService: https://swagger.io/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Store Development Team
    email: STORE-TEAM@example.com
servers:
  - url: http://localhost
    description: local
  - url: https://dev.store.com
    description: development
  - url: https://stage.store.com
    description: stage

paths:
  /pet:
    get:
      tags:
        - "Pet APIs"
      summary: "Retrieve all Pets"
      description: "Returns a collection of Pet"
      operationId: "getPets"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        "400":
          description: Bad Request
    post:
      tags:
        - "Pet APIs"
      summary: "Add a Pet"
      description: "Add a single Pet"
      operationId: "addPet"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request

components:
  schemas:
    Pet:
      type: object
      required:
        - petId
      properties:
        petId:
          type: integer
        name:
          type: string
        color:
          type: string
        birthDate:
          type: string
          format: date-time