name: CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Install dependencies
        uses: ./gradlew

      - name: Lint
        uses: ./gradlew ktfmtCheck

      - name: Prettier check
        uses: ./gradlew ktlintCheck
