name: CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - uses: gradle/gradle-build-action@v2

      - name: Install dependencies
        run: ./gradlew build

      - name: Lint
        run: ./gradlew ktlintCheck

      - name: Prettier check
        run: ./gradlew ktfmtCheck
